#!/bin/bash

BRANCH=main
MAP_DIR=files/etc/adkit/map

mkdir -p $MAP_DIR

(
    cd $MAP_DIR;
    curl -LO https://gitlab.com/autowarefoundation/autoware_reference_design/-/raw/$BRANCH/docs/Appendix/Open-AD-Kit-Start-Guide/map/kashiwanoha/lanelet2_map.osm;
    curl -LO https://gitlab.com/autowarefoundation/autoware_reference_design/-/raw/$BRANCH/docs/Appendix/Open-AD-Kit-Start-Guide/map/kashiwanoha/pointcloud_map.pcd;
)
